# Generated by Django 4.2.4 on 2023-10-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='PlacesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img3d', models.FileField(upload_to='panpictures')),
                ('tradition', models.CharField(max_length=500)),
                ('desc', models.TextField()),
                ('famous_place', models.CharField(max_length=500)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.places')),
            ],
        ),
    ]
