# Generated by Django 4.2.4 on 2023-10-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_places_placesdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesdetail',
            name='language',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placesdetail',
            name='famous_place',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='placesdetail',
            name='tradition',
            field=models.TextField(),
        ),
    ]
