# Generated by Django 4.2.4 on 2023-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_placesdetail_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placesdetail',
            name='famous_place',
        ),
        migrations.RemoveField(
            model_name='placesdetail',
            name='language',
        ),
        migrations.RemoveField(
            model_name='placesdetail',
            name='tradition',
        ),
        migrations.AddField(
            model_name='placesdetail',
            name='cust_trad',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='placesdetail',
            name='famous_spots',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='placesdetail',
            name='img3dname',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='placesdetail',
            name='lang_culture',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='placesdetail',
            name='lang_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='placesdetail',
            name='tips_recom',
            field=models.TextField(default=None),
        ),
    ]
