# Generated by Django 4.2.4 on 2023-10-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_placesdetail_famous_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesdetail',
            name='img1',
            field=models.FileField(default=None, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='placesdetail',
            name='img2',
            field=models.FileField(default=None, upload_to='pictures'),
        ),
    ]
